name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - run: ls -al
    - run: uname -a
    - run: mkdir dd
    - run: cd dd
    - run: touch fdsfs
    - run: ls -al
      
