name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: chmod +x test.sh
    - run: ./test.sh
      env:
        var: ${{ secrets.TEST_VARIABLE }}
    - run: ./test.sh
      
