name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - run: if [ $var -eq 12 ]; then echo "equal"; else echo "not equal"; fi
      env:
        var: ${{ secrets.TEST_VARIABLE }}
      
