name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: chmod +x test.sh
    - run: ./test.sh
      env:
        var: ${{ secrets.TEST_VARIABLE }}
    # GitHub Actions VM 환경의 IP를 받아온다.
    - name: Get Public IP
      id: ip
      uses: haythem/public-ip@v1.3
      
